name: Validate Repository Configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    name: Validate Baseline Configuration
    uses: ./.github/workflows/baseline-validator.yml